spring.application.name=monolith

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce // Assurer vous d'avoir une base de donnees nommee ecommerce
spring.datasource.username=postgres
spring.datasource.password= Mon_mot_de_pass // Remplacer par votre mot de pass reel
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgresPlusDialect
spring.jpa.properties.hibernate.default_schema=ecommerce_app // Assurer vous d'avoir un schema nommee ecommerce_app
spring.datasource.username=postgres

